
project_id = "trkiniaqliiwdkrvvuky"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
# Note: Removed the invalid 'debug' property

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-community-data]
verify_jwt = true

[functions.telegram-user-manager]
verify_jwt = true

[functions.telegram-mini-app]
verify_jwt = true

[functions.send-broadcast]
verify_jwt = false

[functions.check-subscriptions]
verify_jwt = false

[functions.get-telegram-chat-photo]
verify_jwt = true

[functions.kick-member]
verify_jwt = true

[functions.create-invite-link]
verify_jwt = true
